"""create_user_tables

Revision ID: 7a6b96aac112
Revises:
Create Date: 2025-10-31 13:23:59.980655

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a6b96aac112"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("auth_provider_id", sa.String(length=255), nullable=True),
        sa.Column("auth_provider", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_provider_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        "user_auth_provider_id_idx", "users", ["auth_provider_id"], unique=False
    )
    op.create_index(
        "user_created_at_idx",
        "users",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("user_email_idx", "users", ["email"], unique=False)
    op.create_index("user_is_deleted_idx", "users", ["is_deleted"], unique=False)
    op.create_table(
        "user_notification_channels",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_type", sa.String(length=50), nullable=False),
        sa.Column("channel_value", sa.String(length=500), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "user_notification_channel_type_idx",
        "user_notification_channels",
        ["channel_type"],
        unique=False,
    )
    op.create_index(
        "user_notification_channel_user_idx",
        "user_notification_channels",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column(
            "preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_ticker_follows",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("notify_on_signals", sa.Boolean(), nullable=False),
        sa.Column("notify_on_price_change", sa.Boolean(), nullable=False),
        sa.Column("price_change_threshold", sa.Float(), nullable=True),
        sa.Column(
            "custom_alerts", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticker"],
            ["ticker.symbol"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "user_ticker_follow_ticker_idx", "user_ticker_follows", ["ticker"], unique=False
    )
    op.create_index(
        "user_ticker_follow_user_idx", "user_ticker_follows", ["user_id"], unique=False
    )
    op.create_index(
        "user_ticker_follow_user_ticker_idx",
        "user_ticker_follows",
        ["user_id", "ticker"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "user_ticker_follow_user_ticker_idx", table_name="user_ticker_follows"
    )
    op.drop_index("user_ticker_follow_user_idx", table_name="user_ticker_follows")
    op.drop_index("user_ticker_follow_ticker_idx", table_name="user_ticker_follows")
    op.drop_table("user_ticker_follows")
    op.drop_table("user_profiles")
    op.drop_index(
        "user_notification_channel_user_idx", table_name="user_notification_channels"
    )
    op.drop_index(
        "user_notification_channel_type_idx", table_name="user_notification_channels"
    )
    op.drop_table("user_notification_channels")
    op.drop_index("user_is_deleted_idx", table_name="users")
    op.drop_index("user_email_idx", table_name="users")
    op.drop_index("user_created_at_idx", table_name="users")
    op.drop_index("user_auth_provider_id_idx", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
