#!/usr/bin/env python3
"""Clean up problematic ticker aliases that cause false positives."""

import logging

from app.db.models import Ticker
from app.db.session import get_db

logger = logging.getLogger(__name__)

# Common English words that should not be ticker aliases
PROBLEMATIC_ALIASES: set[str] = {
    # Single letters
    "a",
    "i",
    "o",
    # Common two-letter words
    "it",
    "go",
    "do",
    "so",
    "no",
    "up",
    "in",
    "on",
    "at",
    "to",
    "of",
    "is",
    "as",
    "be",
    "or",
    "we",
    "he",
    "me",
    "my",
    "us",
    "am",
    "an",
    "if",
    "by",
    "hi",
    "ok",
    "oh",
    "ah",
    "eh",
    "uh",
    "yo",
    # Common three-letter words
    "the",
    "and",
    "for",
    "are",
    "but",
    "not",
    "you",
    "all",
    "can",
    "had",
    "her",
    "was",
    "one",
    "our",
    "out",
    "day",
    "get",
    "has",
    "him",
    "his",
    "how",
    "its",
    "may",
    "new",
    "now",
    "old",
    "see",
    "two",
    "way",
    "who",
    "boy",
    "did",
    "man",
    "men",
    "put",
    "say",
    "she",
    "too",
    "use",
    "war",
    "win",
    "won",
    "yes",
    "yet",
    "big",
    "buy",
    "car",
    "cut",
    "end",
    "far",
    "few",
    "got",
    "hit",
    "hot",
    "let",
    "lot",
    "low",
    "own",
    "run",
    "set",
    "sit",
    "sun",
    "top",
    "try",
    "why",
    "bad",
    "bag",
    "bed",
    "bit",
    "box",
    "bus",
    "cat",
    "cup",
    "dog",
    "ear",
    "eat",
    "egg",
    "eye",
    "fly",
    "fun",
    "gun",
    "hat",
    "job",
    "key",
    "kid",
    "leg",
    "lie",
    "log",
    "map",
    "mix",
    "net",
    "oil",
    "pay",
    "pen",
    "pie",
    "pig",
    "pot",
    "red",
    "row",
    "sea",
    "six",
    "sky",
    "son",
    "tax",
    "tea",
    "ten",
    "tie",
    "toy",
    "van",
    "web",
    "zip",
    "zoo",
    # Common four-letter words
    "this",
    "that",
    "with",
    "have",
    "will",
    "your",
    "from",
    "they",
    "know",
    "want",
    "been",
    "good",
    "much",
    "some",
    "time",
    "very",
    "when",
    "come",
    "here",
    "just",
    "like",
    "long",
    "make",
    "many",
    "over",
    "such",
    "take",
    "than",
    "them",
    "well",
    "were",
    "what",
    "year",
    "work",
    "back",
    "call",
    "came",
    "each",
    "even",
    "find",
    "give",
    "hand",
    "help",
    "keep",
    "kind",
    "last",
    "late",
    "left",
    "life",
    "line",
    "live",
    "look",
    "made",
    "move",
    "name",
    "need",
    "next",
    "only",
    "open",
    "part",
    "play",
    "read",
    "right",
    "said",
    "same",
    "seem",
    "show",
    "side",
    "tell",
    "turn",
    "used",
    "week",
    "went",
    "word",
    "able",
    "area",
    "away",
    "ball",
    "bank",
    "base",
    "beat",
    "best",
    "bill",
    "blue",
    "book",
    "both",
    "card",
    "care",
    "case",
    "cash",
    "city",
    "cold",
    "cost",
    "data",
    "deal",
    "deep",
    "door",
    "down",
    "draw",
    "drop",
    "east",
    "easy",
    "edge",
    "else",
    "ever",
    "face",
    "fact",
    "fall",
    "fast",
    "feel",
    "feet",
    "fell",
    "felt",
    "fine",
    "fire",
    "firm",
    "fish",
    "five",
    "flat",
    "flow",
    "food",
    "foot",
    "form",
    "four",
    "free",
    "full",
    "game",
    "gave",
    "girl",
    "goal",
    "gone",
    "grew",
    "grow",
    "hard",
    "head",
    "hear",
    "heat",
    "held",
    "high",
    "hill",
    "hold",
    "home",
    "hope",
    "hour",
    "idea",
    "kept",
    "kill",
    "knew",
    "land",
    "lead",
    "less",
    "lift",
    "link",
    "list",
    "load",
    "loan",
    "lock",
    "lost",
    "love",
    "mail",
    "main",
    "male",
    "mark",
    "mass",
    "mind",
    "mine",
    "miss",
    "must",
    "near",
    "news",
    "nice",
    "nine",
    "none",
    "nose",
    "note",
    "okay",
    "once",
    "oral",
    "page",
    "paid",
    "pair",
    "park",
    "pass",
    "past",
    "path",
    "peak",
    "pick",
    "plan",
    "plus",
    "poll",
    "poor",
    "port",
    "post",
    "pull",
    "push",
    "race",
    "rail",
    "rain",
    "rank",
    "rate",
    "real",
    "rear",
    "rest",
    "rich",
    "ride",
    "ring",
    "rise",
    "risk",
    "road",
    "rock",
    "role",
    "roll",
    "room",
    "root",
    "rose",
    "rule",
    "rush",
    "safe",
    "sake",
    "sale",
    "salt",
    "sand",
    "save",
    "seat",
    "seed",
    "seek",
    "seen",
    "self",
    "sell",
    "send",
    "sent",
    "sets",
    "ship",
    "shop",
    "shot",
    "shut",
    "sick",
    "sign",
    "silk",
    "sing",
    "sink",
    "site",
    "size",
    "skin",
    "slip",
    "slow",
    "snap",
    "snow",
    "soft",
    "soil",
    "sold",
    "sole",
    "song",
    "soon",
    "sort",
    "soul",
    "soup",
    "sour",
    "span",
    "spin",
    "spot",
    "star",
    "stay",
    "step",
    "stop",
    "suit",
    "sure",
    "swim",
    "tail",
    "talk",
    "tall",
    "tank",
    "tape",
    "task",
    "team",
    "tear",
    "tend",
    "term",
    "test",
    "text",
    "then",
    "thin",
    "thus",
    "till",
    "tiny",
    "tire",
    "told",
    "toll",
    "tone",
    "took",
    "tool",
    "toss",
    "tour",
    "town",
    "tree",
    "trip",
    "true",
    "tube",
    "tune",
    "twin",
    "type",
    "unit",
    "upon",
    "user",
    "uses",
    "vary",
    "vast",
    "view",
    "vote",
    "wait",
    "wake",
    "walk",
    "wall",
    "ward",
    "warm",
    "warn",
    "wash",
    "wave",
    "ways",
    "weak",
    "wear",
    "west",
    "whip",
    "wide",
    "wife",
    "wild",
    "wind",
    "wine",
    "wing",
    "wire",
    "wise",
    "wish",
    "wolf",
    "wood",
    "wore",
    "worm",
    "worn",
    "wrap",
    "yard",
    "yell",
    "zone",
}

# Important tickers that should keep their common word aliases
IMPORTANT_TICKERS: set[str] = {
    "COST",
    "LOW",
    "V",
    "T",
    "GOOGL",
    "GOOG",
    "META",
    "FB",
    "AMZN",
    "TSLA",
    "NVDA",
    "MSFT",
    "AAPL",
}


def clean_problematic_aliases(dry_run: bool = True) -> None:
    """Remove problematic aliases from tickers.

    Args:
        dry_run: If True, only show what would be changed without making changes
    """
    db = next(get_db())

    changes_made = 0
    tickers_affected = 0

    for ticker in db.query(Ticker).all():
        original_aliases = ticker.aliases.copy()
        cleaned_aliases = []

        for alias in ticker.aliases:
            # Keep the alias if:
            # 1. It's not a problematic common word, OR
            # 2. The ticker is important and should keep common word aliases
            if (
                alias.lower() not in PROBLEMATIC_ALIASES
                or ticker.symbol in IMPORTANT_TICKERS
            ):
                cleaned_aliases.append(alias)
            else:
                if dry_run:
                    print(
                        f"Would remove alias '{alias}' from {ticker.symbol} ({ticker.name})"
                    )
                changes_made += 1

        if len(cleaned_aliases) != len(original_aliases):
            tickers_affected += 1
            if not dry_run:
                ticker.aliases = cleaned_aliases
                db.commit()
                print(
                    f"Cleaned {ticker.symbol}: removed {len(original_aliases) - len(cleaned_aliases)} problematic aliases"
                )

    if dry_run:
        print("\nDRY RUN SUMMARY:")
        print(f"  Would affect {tickers_affected} tickers")
        print(f"  Would remove {changes_made} problematic aliases")
        print("\nTo apply changes, run with --apply flag")
    else:
        print("\nCLEANUP COMPLETE:")
        print(f"  Affected {tickers_affected} tickers")
        print(f"  Removed {changes_made} problematic aliases")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Clean up problematic ticker aliases")
    parser.add_argument(
        "--apply", action="store_true", help="Apply changes (default is dry run)"
    )

    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO)

    clean_problematic_aliases(dry_run=not args.apply)
